### ISSUE TITLE
打印功能

### ISSUE THREAD

**Issue by Qianshaojun** [wyaoting/sunsetglow-vue-pdf-viewer#6]
有打印功能的参数配置吗？还是说没有这个功能？可以添加吗？

**Comment by wyaoting** [comment]
你好，朋友，暂时没有考虑到打印功能，我这两天找个时间加一下。

**Comment by Qianshaojun** [comment]
> 你好，朋友，暂时没有考虑到打印功能，我这两天找个时间加一下。

好的，谢谢

**Comment by Qianshaojun** [comment]
大佬，我用了下最新的，并没有打印的按钮




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wyaoting/sunsetglow-vue-pdf-viewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月17日(星期四) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wyaoting/sunsetglow-vue-pdf-viewer] 打印功能 (Issue #6)





 
你好，朋友，暂时没有考虑到打印功能，我这两天找个时间加一下。

**Comment by wyaoting** [comment]
node 版本是 0.08吗？  pdfOption.print 是否等于 true，或者把node包全部删除重新下载一下

**Comment by Qianshaojun** [comment]
可以了，是npm缓存问题，但是打印的有问题，我只有1页的pdf，打印显示有3页，而且还加上了时间和网页名称







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wyaoting/sunsetglow-vue-pdf-viewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月21日(星期一) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wyaoting/sunsetglow-vue-pdf-viewer] 打印功能 (Issue #6)





 
node 版本是 0.08吗？  pdfOption.print 是否等于 true，或者把node包全部删除重新下载一下

**Comment by wyaoting** [comment]
你好朋友，时间和网页名称可以去除，打印显示三页是啥意思，可以截个图吗
