### ISSUE TITLE
字体加载过程中发生错误：必须指定CMap的“baseUrl”参数，请确保提供了“cMapUrl”和“cMapPacked”API参数。

### ISSUE THREAD

**Issue by LostElkByte** [wyaoting/sunsetglow-vue-pdf-viewer#8]
Warning: loadFont - translateFont failed: "UnknownErrorException: 
The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.".
警告：字体加载过程中发生错误：必须指定CMap的“baseUrl”参数，请确保提供了“cMapUrl”和“cMapPacked”API参数。

原因是有pdf不支持的字体格式
 //解决文字缺少问题
  params.cMapPacked = true
  params.cMapUrl = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.2.228/cmaps/'

**Comment by wyaoting** [comment]
哈喽，朋友，感谢你反馈。这两天我会找时间修复这个问题

**Comment by wyaoting** [comment]
哈喽，朋友你好，配置项加了 版本 0.1.0 [customPdfOption 参数](https://github.com/wyaoting/sunsetglow-vue-pdf-viewer/tree/feat/config)  感谢你的反馈

**Comment by LostElkByte** [comment]
真效率呀！太及时了！！！

**Comment by wyaoting** [comment]
哈哈，很开心帮助到你



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月31日 18:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wyaoting/sunsetglow-vue-pdf-viewer] 字体加载过程中发生错误：必须指定CMap的“baseUrl”参数，请确保提供了“cMapUrl”和“cMapPacked”API参数。 (Issue #8) |

真效率呀！太及时了！！！
